(define "para_ammo"
	{extender "supply_zone"
		{resupply
            {item "22lr_176" 			"ammo" 176 	{max 352}}
			{item "47g11_45" 			"ammo" 45 	{max 315}}
			{item "338_5" 				"ammo" 5 	{max 35}}
			{item "918_8" 				"ammo" 8 	{max 32}}
			{item "918_20" 				"ammo" 20 	{max 60}}
			{item "918_25" 				"ammo" 25 	{max 100}}
			{item "919_8" 				"ammo" 8 	{max 32}}
			{item "919_13" 				"ammo" 13 	{max 52}}
			{item "919_15" 				"ammo" 15 	{max 60}}
			{item "919_17" 				"ammo" 17 	{max 68}}
			{item "919_30" 				"ammo" 30 	{max 210}}
			{item "919_30fr" 			"ammo" 30 	{max 210}}
			{item "919_30jp" 			"ammo" 30 	{max 210}}
			{item "919_32" 				"ammo" 32 	{max 224}}
			{item "919_34" 				"ammo" 34 	{max 238}}
			{item "919_36" 				"ammo" 36 	{max 252}}
			{item "919_40" 				"ammo" 40 	{max 280}}
			{item "939_20" 				"ammo" 20 	{max 140}}
			{item "1143_7" 				"ammo" 7 	{max 28}}
			{item "1143_20_thompson" 	"ammo" 20 	{max 200}}
			{item "1143_30" 			"ammo" 30 	{max 150}}
			{item "5821_15" 			"ammo" 15 	{max 105}}
			{item "5842_10" 			"ammo" 10 	{max 70}}
			{item "5842_75" 			"ammo" 75 	{max 450}}
			{item "5842_200" 			"ammo" 200 	{max 600}}
			{item "12799_5" 			"ammo" 10	{max 35}}
			{item "12799_10" 			"ammo" 10	{max 70}}
			{item "12799_100" 			"ammo" 100	{max 900}}
			{item "54539_30" 			"ammo" 30 	{max 210}}
			{item "54539_45" 			"ammo" 45 	{max 540}}
			{item "54539_75" 			"ammo" 75 	{max 450}}
			{item "55645_20" 			"ammo" 20 	{max 140}}
			{item "55645_20sg" 			"ammo" 20 	{max 140}}
			{item "55645_25fr" 			"ammo" 25 	{max 175}}
			{item "55645_25hk" 			"ammo" 25 	{max 175}}
			{item "55645_30ar" 			"ammo" 30 	{max 210}}
			{item "55645_30aug" 		"ammo" 30 	{max 210}}
			{item "55645_30g36" 		"ammo" 30 	{max 210}}
			{item "55645_30jp" 			"ammo" 30 	{max 210}}
			{item "55645_30za" 			"ammo" 30 	{max 210}}
			{item "55645_35" 			"ammo" 35 	{max 245}}
			{item "55645_200" 			"ammo" 200 	{max 800}}
			{item "5842_30" 			"ammo" 30 	{max 210}}
			{item "75054_5" 			"ammo" 5 	{max 35}}
			{item "75054_10" 			"ammo" 10 	{max 70}}
			{item "75054_100" 			"ammo" 100	{max 600}}
			{item "76217_9" 			"ammo" 9 	{max 36}}
			{item "76225_8" 			"ammo" 8 	{max 32}}
			{item "76225_9" 			"ammo" 9 	{max 36}}
			{item "76225_20" 			"ammo" 20 	{max 140}}
			{item "76225_30" 			"ammo" 30 	{max 210}}
			{item "76225_35" 			"ammo" 35 	{max 245}}
			{item "76225_71" 			"ammo" 71 	{max 213}}
			{item "76239_10" 			"ammo" 10 	{max 70}}
			{item "76239_20" 			"ammo" 20 	{max 140}}
			{item "76239_30" 			"ammo" 30 	{max 210}}
			{item "76239_40" 			"ammo" 30 	{max 540}}
			{item "76239_75" 			"ammo" 75 	{max 450}}
			{item "76239_100" 			"ammo" 100	{max 600}}
			{item "76242_6" 			"ammo" 6 	{max 24}}
			{item "76251_5" 			"ammo" 5 	{max 35}}
			{item "76251_10aw" 			"ammo" 10 	{max 70}}
			{item "76251_10fr" 			"ammo" 10 	{max 70}}
			{item "76251_20fn" 			"ammo" 20 	{max 140}}
			{item "76251_20g3" 			"ammo" 20 	{max 140}}
			{item "76251_20m14" 		"ammo" 20 	{max 140}}
			{item "76251_20jp" 			"ammo" 20 	{max 140}}
			{item "76251_30bren" 		"ammo" 30 	{max 210}}
			{item "76251_35" 			"ammo" 35 	{max 245}}
			{item "76251_100" 			"ammo" 100	{max 600}}
			{item "76254_10" 			"ammo" 10 	{max 70}}
			{item "76254_30" 			"ammo" 30 	{max 360}}
			{item "76254_50" 			"ammo" 50 	{max 600}}
			{item "76254_100" 			"ammo" 100	{max 600}}
			{item "76263_20" 			"ammo" 20	{max 140}}
			{item "76263_100" 			"ammo" 100	{max 600}}
			{item "76517_20" 			"ammo" 20 	{max 140}}
			{item "79257_10" 			"ammo" 10 	{max 70}}
			{item "79257_50" 			"ammo" 50 	{max 300}}
			{item "127108_100" 			"ammo" 200	{max 1200}}
			{item "size12_ammo" 		"ammo" 10 	{max 80}}
			{item "hmgun" 				"ammo" 50 	{max 300}	{value 2}}
			;>>
			{item "grenade" 			"decoy" 1 	{max 1}		{value 2}}
			{item "bandage"						1 	{max 5}}
			;>>
			{item "agi3x40_rocket" 		"ammo" 1 {max 6}}
			{item "carl_gustav_rocket" 	"ammo" 1 {max 6}}			
			{item "law80_rocket" 		"ammo" 1 {max 6}}
			{item "lrac73_rocket" 		"ammo" 1 {max 6}}	
			{item "lracf1_rocket" 		"ammo" 1 {max 6}}		
			{item "m20a1_rocket" 		"ammo" 1 {max 6}}	
			{item "m57a2_rocket" 		"ammo" 1 {max 6}}	
			{item "m67_rocket" 			"ammo" 1 {max 6}}
			{item "m79rpg_rocket" 		"ammo" 1 {max 6}}		
			{item "m202_rocket" 		"ammo" 1 {max 6}}
			{item "m386_rifle_grenade" 	"ammo" 1 {max 24}}
			{item "vog25_rifle_grenade" "ammo" 1 {max 24}}			
			{item "p27rpg_rocket" 		"ammo" 1 {max 6}}			
			{item "panzerfaust3_rocket" "ammo" 1 {max 6}}		
			{item "pf98_rocket" 		"ammo" 1 {max 6}}		
			{item "rl100_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg7_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg29_rocket" 		"ammo" 1 {max 6}}			
			{item "smaw_rocket" 		"ammo" 1 {max 6}}			
			{item "type56_rocket" 		"ammo" 1 {max 6}}		
			{item "type65_rocket" 		"ammo" 1 {max 6}}		
			{item "type67_rifle_grenade" "ammo" 1 {max 24}}		
			{item "type69_rocket" 		"ammo" 1 {max 6}}		
			{item "type70_rocket" 		"ammo" 1 {max 6}}
			{item "type89_rocket" 		"ammo" 1 {max 6}}
			;>>
			{item "mortar" "fg" 		"ammo" 5 {max 30}		{value 2}}
			{item "mortar107" "fg" 		"ammo" 5 {max 30}		{value 2}}
			{item "mortar120" "fg" 		"ammo" 5 {max 30}		{value 2}}		
		}
		{radius 			7}		;resupply radius in meter
		{resupplyPeriod 	2}		;resupply period in seconds
		{regenerationPeriod 0}		;regeneration period in seconds, +1 supply every x seconds (0 = no regeneration)
		{limit 				350}	;max number of resupplies (0 = unlimited)
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.8}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "truck_ammo"
	{extender "supply_zone"
		{resupply
            {item "22lr_176" 			"ammo" 176 	{max 352}}
			{item "47g11_45" 			"ammo" 45 	{max 315}}
			{item "338_5" 				"ammo" 5 	{max 35}}
			{item "918_8" 				"ammo" 8 	{max 32}}
			{item "918_20" 				"ammo" 20 	{max 60}}
			{item "918_25" 				"ammo" 25 	{max 100}}
			{item "919_8" 				"ammo" 8 	{max 32}}
			{item "919_13" 				"ammo" 13 	{max 52}}
			{item "919_15" 				"ammo" 15 	{max 60}}
			{item "919_17" 				"ammo" 17 	{max 68}}
			{item "919_30" 				"ammo" 30 	{max 210}}
			{item "919_30fr" 			"ammo" 30 	{max 210}}
			{item "919_30jp" 			"ammo" 30 	{max 210}}
			{item "919_32" 				"ammo" 32 	{max 224}}
			{item "919_34" 				"ammo" 34 	{max 238}}
			{item "919_36" 				"ammo" 36 	{max 252}}
			{item "919_40" 				"ammo" 40 	{max 280}}
			{item "939_20" 				"ammo" 20 	{max 140}}
			{item "1143_7" 				"ammo" 7 	{max 28}}
			{item "1143_20_thompson" 	"ammo" 20 	{max 200}}
			{item "1143_30" 			"ammo" 30 	{max 150}}
			{item "5821_15" 			"ammo" 15 	{max 105}}
			{item "5842_10" 			"ammo" 10 	{max 70}}
			{item "5842_75" 			"ammo" 75 	{max 450}}
			{item "5842_200" 			"ammo" 200 	{max 600}}
			{item "12799_5" 			"ammo" 10	{max 35}}
			{item "12799_10" 			"ammo" 10	{max 70}}
			{item "12799_100" 			"ammo" 100	{max 900}}
			{item "54539_30" 			"ammo" 30 	{max 210}}
			{item "54539_45" 			"ammo" 45 	{max 540}}
			{item "54539_75" 			"ammo" 75 	{max 450}}
			{item "55645_20" 			"ammo" 20 	{max 140}}
			{item "55645_20sg" 			"ammo" 20 	{max 140}}
			{item "55645_25fr" 			"ammo" 25 	{max 175}}
			{item "55645_25hk" 			"ammo" 25 	{max 175}}
			{item "55645_30ar" 			"ammo" 30 	{max 210}}
			{item "55645_30aug" 		"ammo" 30 	{max 210}}
			{item "55645_30g36" 		"ammo" 30 	{max 210}}
			{item "55645_30jp" 			"ammo" 30 	{max 210}}
			{item "55645_30za" 			"ammo" 30 	{max 210}}
			{item "55645_35" 			"ammo" 35 	{max 245}}
			{item "55645_200" 			"ammo" 200 	{max 800}}
			{item "5842_30" 			"ammo" 30 	{max 210}}
			{item "75054_5" 			"ammo" 5 	{max 35}}
			{item "75054_10" 			"ammo" 10 	{max 70}}
			{item "75054_100" 			"ammo" 100	{max 600}}
			{item "76217_9" 			"ammo" 9 	{max 36}}
			{item "76225_8" 			"ammo" 8 	{max 32}}
			{item "76225_9" 			"ammo" 9 	{max 36}}
			{item "76225_20" 			"ammo" 20 	{max 140}}
			{item "76225_30" 			"ammo" 30 	{max 210}}
			{item "76225_35" 			"ammo" 35 	{max 245}}
			{item "76225_71" 			"ammo" 71 	{max 213}}
			{item "76239_10" 			"ammo" 10 	{max 70}}
			{item "76239_20" 			"ammo" 20 	{max 140}}
			{item "76239_30" 			"ammo" 30 	{max 210}}
			{item "76239_40" 			"ammo" 30 	{max 540}}
			{item "76239_75" 			"ammo" 75 	{max 450}}
			{item "76239_100" 			"ammo" 100	{max 600}}
			{item "76242_6" 			"ammo" 6 	{max 24}}
			{item "76251_5" 			"ammo" 5 	{max 35}}
			{item "76251_10aw" 			"ammo" 10 	{max 70}}
			{item "76251_10fr" 			"ammo" 10 	{max 70}}
			{item "76251_20fn" 			"ammo" 20 	{max 140}}
			{item "76251_20g3" 			"ammo" 20 	{max 140}}
			{item "76251_20m14" 		"ammo" 20 	{max 140}}
			{item "76251_20jp" 			"ammo" 20 	{max 140}}
			{item "76251_30bren" 		"ammo" 30 	{max 210}}
			{item "76251_35" 			"ammo" 35 	{max 245}}
			{item "76251_100" 			"ammo" 100	{max 600}}
			{item "76254_10" 			"ammo" 10 	{max 70}}
			{item "76254_30" 			"ammo" 30 	{max 360}}
			{item "76254_50" 			"ammo" 50 	{max 600}}
			{item "76254_100" 			"ammo" 100	{max 600}}
			{item "76263_20" 			"ammo" 20	{max 140}}
			{item "76263_100" 			"ammo" 100	{max 600}}
			{item "76517_20" 			"ammo" 20 	{max 140}}
			{item "79257_10" 			"ammo" 10 	{max 70}}
			{item "79257_50" 			"ammo" 50 	{max 300}}
			{item "127108_100" 			"ammo" 200	{max 1200}}
			{item "size12_ammo" 		"ammo" 10 	{max 80}}
			{item "hmgun" 				"ammo" 50 	{max 300}	{value 2}}
			;>>
			{item "grenade" 			"decoy" 1 	{max 1}		{value 2}}
			{item "bandage"						1 	{max 5}}
			;>>
			{item "agi3x40_rocket" 		"ammo" 1 {max 6}}
			{item "carl_gustav_rocket" 	"ammo" 1 {max 6}}			
			{item "law80_rocket" 		"ammo" 1 {max 6}}
			{item "lrac73_rocket" 		"ammo" 1 {max 6}}	
			{item "lracf1_rocket" 		"ammo" 1 {max 6}}		
			{item "m20a1_rocket" 		"ammo" 1 {max 6}}	
			{item "m57a2_rocket" 		"ammo" 1 {max 6}}	
			{item "m67_rocket" 			"ammo" 1 {max 6}}
			{item "m79rpg_rocket" 		"ammo" 1 {max 6}}		
			{item "m202_rocket" 		"ammo" 1 {max 6}}
			{item "m386_rifle_grenade" 	"ammo" 1 {max 24}}
			{item "vog25_rifle_grenade" "ammo" 1 {max 24}}			
			{item "p27rpg_rocket" 		"ammo" 1 {max 6}}			
			{item "panzerfaust3_rocket" "ammo" 1 {max 6}}		
			{item "pf98_rocket" 		"ammo" 1 {max 6}}		
			{item "rl100_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg7_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg29_rocket" 		"ammo" 1 {max 6}}			
			{item "smaw_rocket" 		"ammo" 1 {max 6}}			
			{item "type56_rocket" 		"ammo" 1 {max 6}}		
			{item "type65_rocket" 		"ammo" 1 {max 6}}		
			{item "type67_rifle_grenade" "ammo" 1 {max 24}}		
			{item "type69_rocket" 		"ammo" 1 {max 6}}		
			{item "type70_rocket" 		"ammo" 1 {max 6}}
			{item "type89_rocket" 		"ammo" 1 {max 6}}
			;>>
			{item "mortar" "fg" 		"ammo" 5 {max 30}		{value 2}}
			{item "mortar107" "fg" 		"ammo" 5 {max 30}		{value 2}}
			{item "mortar120" "fg" 		"ammo" 5 {max 30}		{value 2}}
		}
		{radius 			8}
		{resupplyPeriod 	1}
		{regenerationPeriod 30}
		{limit 				800}
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.8}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "truck_ammo_art"
	{extender "supply_zone"
		{resupply
            {item "22lr_176" 			"ammo" 176 	{max 352}}
			{item "47g11_45" 			"ammo" 45 	{max 315}}
			{item "338_5" 				"ammo" 5 	{max 35}}
			{item "918_8" 				"ammo" 8 	{max 32}}
			{item "918_20" 				"ammo" 20 	{max 60}}
			{item "918_25" 				"ammo" 25 	{max 100}}
			{item "919_8" 				"ammo" 8 	{max 32}}
			{item "919_13" 				"ammo" 13 	{max 52}}
			{item "919_15" 				"ammo" 15 	{max 60}}
			{item "919_17" 				"ammo" 17 	{max 68}}
			{item "919_30" 				"ammo" 30 	{max 210}}
			{item "919_30fr" 			"ammo" 30 	{max 210}}
			{item "919_30jp" 			"ammo" 30 	{max 210}}
			{item "919_32" 				"ammo" 32 	{max 224}}
			{item "919_34" 				"ammo" 34 	{max 238}}
			{item "919_36" 				"ammo" 36 	{max 252}}
			{item "919_40" 				"ammo" 40 	{max 280}}
			{item "939_20" 				"ammo" 20 	{max 140}}
			{item "1143_7" 				"ammo" 7 	{max 28}}
			{item "1143_20_thompson" 	"ammo" 20 	{max 200}}
			{item "1143_30" 			"ammo" 30 	{max 150}}
			{item "5821_15" 			"ammo" 15 	{max 105}}
			{item "5842_10" 			"ammo" 10 	{max 70}}
			{item "5842_75" 			"ammo" 75 	{max 450}}
			{item "5842_200" 			"ammo" 200 	{max 600}}
			{item "12799_5" 			"ammo" 10	{max 35}}
			{item "12799_10" 			"ammo" 10	{max 70}}
			{item "12799_100" 			"ammo" 100	{max 900}}
			{item "54539_30" 			"ammo" 30 	{max 210}}
			{item "54539_45" 			"ammo" 45 	{max 540}}
			{item "54539_75" 			"ammo" 75 	{max 450}}
			{item "55645_20" 			"ammo" 20 	{max 140}}
			{item "55645_20sg" 			"ammo" 20 	{max 140}}
			{item "55645_25fr" 			"ammo" 25 	{max 175}}
			{item "55645_25hk" 			"ammo" 25 	{max 175}}
			{item "55645_30ar" 			"ammo" 30 	{max 210}}
			{item "55645_30aug" 		"ammo" 30 	{max 210}}
			{item "55645_30g36" 		"ammo" 30 	{max 210}}
			{item "55645_30jp" 			"ammo" 30 	{max 210}}
			{item "55645_30za" 			"ammo" 30 	{max 210}}
			{item "55645_35" 			"ammo" 35 	{max 245}}
			{item "55645_200" 			"ammo" 200 	{max 800}}
			{item "5842_30" 			"ammo" 30 	{max 210}}
			{item "75054_5" 			"ammo" 5 	{max 35}}
			{item "75054_10" 			"ammo" 10 	{max 70}}
			{item "75054_100" 			"ammo" 100	{max 600}}
			{item "76217_9" 			"ammo" 9 	{max 36}}
			{item "76225_8" 			"ammo" 8 	{max 32}}
			{item "76225_9" 			"ammo" 9 	{max 36}}
			{item "76225_20" 			"ammo" 20 	{max 140}}
			{item "76225_30" 			"ammo" 30 	{max 210}}
			{item "76225_35" 			"ammo" 35 	{max 245}}
			{item "76225_71" 			"ammo" 71 	{max 213}}
			{item "76239_10" 			"ammo" 10 	{max 70}}
			{item "76239_20" 			"ammo" 20 	{max 140}}
			{item "76239_30" 			"ammo" 30 	{max 210}}
			{item "76239_40" 			"ammo" 30 	{max 540}}
			{item "76239_75" 			"ammo" 75 	{max 450}}
			{item "76239_100" 			"ammo" 100	{max 600}}
			{item "76242_6" 			"ammo" 6 	{max 24}}
			{item "76251_5" 			"ammo" 5 	{max 35}}
			{item "76251_10aw" 			"ammo" 10 	{max 70}}
			{item "76251_10fr" 			"ammo" 10 	{max 70}}
			{item "76251_20fn" 			"ammo" 20 	{max 140}}
			{item "76251_20g3" 			"ammo" 20 	{max 140}}
			{item "76251_20m14" 		"ammo" 20 	{max 140}}
			{item "76251_20jp" 			"ammo" 20 	{max 140}}
			{item "76251_30bren" 		"ammo" 30 	{max 210}}
			{item "76251_35" 			"ammo" 35 	{max 245}}
			{item "76251_100" 			"ammo" 100	{max 600}}
			{item "76254_10" 			"ammo" 10 	{max 70}}
			{item "76254_30" 			"ammo" 30 	{max 360}}
			{item "76254_50" 			"ammo" 50 	{max 600}}
			{item "76254_100" 			"ammo" 100	{max 600}}
			{item "76263_20" 			"ammo" 20	{max 140}}
			{item "76263_100" 			"ammo" 100	{max 600}}
			{item "76517_20" 			"ammo" 20 	{max 140}}
			{item "79257_10" 			"ammo" 10 	{max 70}}
			{item "79257_50" 			"ammo" 50 	{max 300}}
			{item "127108_100" 			"ammo" 200	{max 1200}}
			{item "size12_ammo" 		"ammo" 10 	{max 80}}
			{item "hmgun" 				"ammo" 50 	{max 300}	{value 2}}
			;>>
			{item "grenade" 			"decoy" 1 	{max 1}		{value 2}}
			{item "bandage"						1 	{max 5}}
			;>>
			{item "agi3x40_rocket" 		"ammo" 1 {max 6}}
			{item "carl_gustav_rocket" 	"ammo" 1 {max 6}}			
			{item "law80_rocket" 		"ammo" 1 {max 6}}
			{item "lrac73_rocket" 		"ammo" 1 {max 6}}	
			{item "lracf1_rocket" 		"ammo" 1 {max 6}}		
			{item "m20a1_rocket" 		"ammo" 1 {max 6}}	
			{item "m57a2_rocket" 		"ammo" 1 {max 6}}	
			{item "m67_rocket" 			"ammo" 1 {max 6}}
			{item "m79rpg_rocket" 		"ammo" 1 {max 6}}		
			{item "m202_rocket" 		"ammo" 1 {max 6}}
			{item "m386_rifle_grenade" 	"ammo" 1 {max 24}}
			{item "vog25_rifle_grenade" "ammo" 1 {max 24}}			
			{item "p27rpg_rocket" 		"ammo" 1 {max 6}}			
			{item "panzerfaust3_rocket" "ammo" 1 {max 6}}		
			{item "pf98_rocket" 		"ammo" 1 {max 6}}		
			{item "rl100_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg7_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg29_rocket" 		"ammo" 1 {max 6}}			
			{item "smaw_rocket" 		"ammo" 1 {max 6}}			
			{item "type56_rocket" 		"ammo" 1 {max 6}}		
			{item "type65_rocket" 		"ammo" 1 {max 6}}		
			{item "type67_rifle_grenade" "ammo" 1 {max 24}}		
			{item "type69_rocket" 		"ammo" 1 {max 6}}		
			{item "type70_rocket" 		"ammo" 1 {max 6}}	
			{item "type89_rocket" 		"ammo" 1 {max 6}}
			;>>
			{item "mortar" 		"fg" 	"ammo" 5 {max 30}	{value 2}}
			{item "mortar107" 	"fg" 	"ammo" 5 {max 30}	{value 2}}
			{item "mortar120" 	"fg" 	"ammo" 5 {max 30}	{value 2}}
			;>>
			{item "bullet20" 	"zenite" "ammo" 10 {max 100}{value 2}}
			{item "bullet23" 	"zenite" "ammo" 500 {max 8000}{value 2}}
			{item "bullet25" 	"zenite" "ammo" 600 {max 2000}{value 2}}
			{item "bullet30" 	"fg" "ammo" 90 {max 1000}{value 2}}
			{item "bullet30" 	"zenite" "ammo" 600 {max 2000}{value 2}}
			{item "bullet35" 	"zenite" "ammo" 600 {max 1000}{value 2}}
			{item "bullet37" 	"zenite" "ammo" 10 {max 600}{value 2}}
			{item "bullet40" 	"fg" "ammo" 100 {max 1200}{value 2}}
			{item "bullet40" 	"zenite" "ammo" 10 {max 600}{value 2}}
			{item "bullet57" 	"ap" 	"ammo" 3 {max 30}{value 2}}
			{item "bullet57" 	"fg" 	"ammo" 3 {max 25}{value 2}}
			{item "bullet73" 	"ap" 	"ammo" 3 {max 30}{value 2}}
			{item "bullet73" 	"fg" 	"ammo" 3 {max 25}{value 2}}
			{item "bullet76" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet76" 	"apcr" 	"ammo" 2 {max 10}{value 2}}
			{item "bullet76" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet76" 	"heat" 	"ammo" 1 {max 10}{value 5}}
			{item "bullet76" 	"hesh" 	"ammo" 1 {max 10}{value 5}}
			{item "bullet82" 	"ap" 	"ammo" 3 {max 30}{value 2}}
			{item "bullet82" 	"fg" 	"ammo" 3 {max 25}{value 2}}	
			{item "bullet85" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet85" 	"apcr" 	"ammo" 2 {max 10}{value 2}}
			{item "bullet85" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet85" 	"heat" 	"ammo" 1 {max 10}{value 5}}
			{item "bullet90" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet90" 	"apcr" 	"ammo" 2 {max 10}{value 2}}
			{item "bullet90" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet90" 	"heat" 	"ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet90usa" "ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet90usa" "apcr" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet90usa" "fg" 	"ammo" 2 {max 15}{value 2}}	
			{item "bullet90usa" "heat" 	"ammo" 2 {max 20}{value 2}}	
			;>>
			{item "bullet100b" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			;>>
			{item "bullet100" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"ap_a" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"ap_b" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"ap_c" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"apcr" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"apds" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet100" 	"heat" 	"ammo" 2 {max 10}{value 2}}
			;>>
			{item "bullet100chi" "ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100chi" "apds" "ammo" 2 {max 20}{value 2}}
			{item "bullet100chi" "fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet100chi" "heat" "ammo" 2 {max 10}{value 2}}
			;>>
			{item "bullet105usa" "ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_a" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_b" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_c" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_d" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "heat" "ammo" 1 {max 10}{value 5}}
			{item "bullet105usa" "heat_a" "ammo" 1 {max 10}{value 5}}
			{item "bullet105usa" "hesh" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet105fra" "ap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105fra" "ap_a" "ammo" 2 {max 20}{value 2}}
			{item "bullet105fra" "fg" "ammo" 1 {max 10}{value 5}}
			{item "bullet105fra" "heat" "ammo" 1 {max 10}{value 5}}
			{item "bullet105fra" "heat_a" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet105" "ap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "ap_a" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "ap_b" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "ap_jap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "fg" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "heat" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "heat_jap" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "hesh" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "hesh_jap" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet105chi" "ap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105chi" "hesh" "ammo" 1 {max 10}{value 5}}
			{item "bullet105chi" "heat" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet106" "ap" "ammo" 2 {max 15}{value 2}}
			{item "bullet106" "fg" "ammo" 1 {max 10}{value 2}}
			;>>
			{item "bullet115" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"ap_a" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"ap_b" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"ap_c" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"fg" 		"ammo" 2 	{max 15}	{value 2}}
			{item "bullet115" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet115" 	"heat_a" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120usa" "ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120usa" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120usa" "heat" 	"ammo" 1 	{max 10}	{value 5}}
			{item "bullet120usa" "mpat" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120fra" "ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120fra" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120fra" "heat" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120brit" "ap"   	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_b" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_c" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_d" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "hesh" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120" 	"ap_a" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120" 	"ap_b" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet120" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120rcl" "hesh" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet122" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet122" 	"apcr" 		"ammo" 2 	{max 10}	{value 2}}
			{item "bullet122" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet125" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_a" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_a_yug" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_b" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_c" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_d" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet125" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet125chi" "ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125chi" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125chi" "fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet125chi" "heat" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet125b" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125b" 	"apu" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125b" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet125b" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet130" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet152" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet152" 	"cluster" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet152_m551" "heat" 	"ammo" 1 	{max 12}	{value 5}}
			{item "bullet152_m551" "fg" 	"ammo" 1 	{max 17}	{value 5}}
			;>>
			{item "bullet155" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet155" 	"cluster" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet165" 	"hesh" 			   1 	{max 10}	{value 5}}
			;>>
			{item "bullet170" 	"fg" 		"ammo" 1 	{max 5}		{value 5}}
			{item "bullet203" 	"fg" 		"ammo" 1 	{max 5}		{value 5}}
			;>>
			{item "rocket57" 	"fg" 		"ammo" 10 	{max 60}	{value 2}}
			{item "rocket70" 	"fg" 		"ammo" 7 	{max 14}	{value 2}}
			{item "rocket70_a" 	"fg" 		"ammo" 20 	{max 80}	{value 2}}
			{item "rocket80" 	"fg" 		"ammo" 20 	{max 80}	{value 2}}
			;>>
			{item "bullet100" 	"arkan" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet100" 	"bastion" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet115" 	"arkan"  	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"angora" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"kobra" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"invar" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"refleks" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"sheksna" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"svir" 		"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125b" 	"9m125" 	"ammo" 1 	{max 5}		{value 5}}	
			;>>
			{item "9m33" 					"ammo" 4 	{max 8}		{value 5}}
			{item "9m311" 					"ammo" 4 	{max 8}		{value 5}}
			{item "9m333" 					"ammo" 4 	{max 8}		{value 5}}
			{item "igla" 					"ammo" 1 	{max 8}		{value 5}}
			{item "stinger" 				"ammo" 1 	{max 8}		{value 5}}
			{item "roland" 					"ammo" 1 	{max 8}		{value 5}}
			{item "rapier" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hq61a" 					"ammo" 4 	{max 8}		{value 5}}
			;>>
			{item "9k127" 					"ammo" 6 	{max 24}	{value 20}}
			{item "9m120" 					"ammo" 4 	{max 16}	{value 20}}
			{item "bulsae" 					"ammo" 5 	{max 8}		{value 5}}
			{item "dragon" 					"ammo" 1 	{max 4}		{value 5}}
			{item "fagot"	 				"ammo" 1 	{max 8}		{value 5}}
			{item "hellfire" 				"ammo" 4 	{max 8}		{value 20}}
			{item "hj8" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hj9" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hj73" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hot" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hot3"					"ammo" 4 	{max 8}		{value 20}}
			{item "itow"					"ammo" 1 	{max 8}		{value 5}}
			{item "jyu_mat" 				"ammo" 1 	{max 8}		{value 5}}
			{item "konkurs" 				"ammo" 4 	{max 8}		{value 5}}
			{item "malyutka" 				"ammo" 4 	{max 8}		{value 5}}
			{item "milan" 					"ammo" 1 	{max 8}		{value 5}}
			{item "milan2" 					"ammo" 1 	{max 8}		{value 5}}
			{item "pars" 					"ammo" 4 	{max 8}		{value 20}}
			{item "ss11" 					"ammo" 1 	{max 8}		{value 5}}
			{item "susongpo" 				"ammo" 4 	{max 8}		{value 5}}
			{item "swingfire" 				"ammo" 1 	{max 8}		{value 5}}
			{item "tow" 					"ammo" 1 	{max 8}		{value 5}}
			{item "tow2" 					"ammo" 1 	{max 8}		{value 5}}
			;>>
			{item "rocket57_b" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket70_b" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket106" 	"fg" 		"ammo" 4 	{max 38}	{value 5}}
			{item "rocket110" 	"fg" 		"ammo" 8 	{max 72}	{value 5}}
			{item "rocket122" 	"fg" 		"ammo" 10 	{max 80}	{value 5}}
			{item "rocket122" 	"mine" 		"ammo" 10 	{max 80}	{value 5}}
			{item "rocket122" 	"tbc" 		"ammo" 10 	{max 80}	{value 5}}
			{item "rocket128" 	"fg" 		"ammo" 4 	{max 64}	{value 5}}
			{item "rocket128_a" "fg" 		"ammo" 8 	{max 64}	{value 5}}
			{item "rocket220" 	"fg" 		"ammo" 4 	{max 32}	{value 5}}
			{item "rocket227" 	"cluster" 	"ammo" 6 	{max 24}	{value 5}}
			{item "rocket227" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket240" 	"fg" 		"ammo" 6 	{max 48}	{value 5}}
			{item "rocket262" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket300" 	"cluster" 	"ammo" 6 	{max 24}	{value 5}}
			{item "rocket300" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket300" 	"tbc" 		"ammo" 6 	{max 24}	{value 5}}
		}
		{radius 			10}
		{resupplyPeriod 	2}
		{regenerationPeriod 30}
		{limit 				2000}
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.8}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "box_ammo"
	{extender "supply_zone"
		{resupply
            {item "22lr_176" 			"ammo" 176 	{max 352}}
			{item "47g11_45" 			"ammo" 45 	{max 315}}
			{item "338_5" 				"ammo" 5 	{max 35}}
			{item "918_8" 				"ammo" 8 	{max 32}}
			{item "918_20" 				"ammo" 20 	{max 60}}
			{item "918_25" 				"ammo" 25 	{max 100}}
			{item "919_8" 				"ammo" 8 	{max 32}}
			{item "919_13" 				"ammo" 13 	{max 52}}
			{item "919_15" 				"ammo" 15 	{max 60}}
			{item "919_17" 				"ammo" 17 	{max 68}}
			{item "919_30" 				"ammo" 30 	{max 210}}
			{item "919_30fr" 			"ammo" 30 	{max 210}}
			{item "919_30jp" 			"ammo" 30 	{max 210}}
			{item "919_32" 				"ammo" 32 	{max 224}}
			{item "919_34" 				"ammo" 34 	{max 238}}
			{item "919_36" 				"ammo" 36 	{max 252}}
			{item "919_40" 				"ammo" 40 	{max 280}}
			{item "939_20" 				"ammo" 20 	{max 140}}
			{item "1143_7" 				"ammo" 7 	{max 28}}
			{item "1143_20_thompson" 	"ammo" 20 	{max 200}}
			{item "1143_30" 			"ammo" 30 	{max 150}}
			{item "5821_15" 			"ammo" 15 	{max 105}}
			{item "5842_10" 			"ammo" 10 	{max 70}}
			{item "5842_75" 			"ammo" 75 	{max 450}}
			{item "5842_200" 			"ammo" 200 	{max 600}}
			{item "12799_5" 			"ammo" 10	{max 35}}
			{item "12799_10" 			"ammo" 10	{max 70}}
			{item "12799_100" 			"ammo" 100	{max 900}}
			{item "54539_30" 			"ammo" 30 	{max 210}}
			{item "54539_45" 			"ammo" 45 	{max 540}}
			{item "54539_75" 			"ammo" 75 	{max 450}}
			{item "55645_20" 			"ammo" 20 	{max 140}}
			{item "55645_20sg" 			"ammo" 20 	{max 140}}
			{item "55645_25fr" 			"ammo" 25 	{max 175}}
			{item "55645_25hk" 			"ammo" 25 	{max 175}}
			{item "55645_30ar" 			"ammo" 30 	{max 210}}
			{item "55645_30aug" 		"ammo" 30 	{max 210}}
			{item "55645_30g36" 		"ammo" 30 	{max 210}}
			{item "55645_30jp" 			"ammo" 30 	{max 210}}
			{item "55645_30za" 			"ammo" 30 	{max 210}}
			{item "55645_35" 			"ammo" 35 	{max 245}}
			{item "55645_200" 			"ammo" 200 	{max 800}}
			{item "5842_30" 			"ammo" 30 	{max 210}}
			{item "75054_5" 			"ammo" 5 	{max 35}}
			{item "75054_10" 			"ammo" 10 	{max 70}}
			{item "75054_100" 			"ammo" 100	{max 600}}
			{item "76217_9" 			"ammo" 9 	{max 36}}
			{item "76225_8" 			"ammo" 8 	{max 32}}
			{item "76225_9" 			"ammo" 9 	{max 36}}
			{item "76225_20" 			"ammo" 20 	{max 140}}
			{item "76225_30" 			"ammo" 30 	{max 210}}
			{item "76225_35" 			"ammo" 35 	{max 245}}
			{item "76225_71" 			"ammo" 71 	{max 213}}
			{item "76239_10" 			"ammo" 10 	{max 70}}
			{item "76239_20" 			"ammo" 20 	{max 140}}
			{item "76239_30" 			"ammo" 30 	{max 210}}
			{item "76239_40" 			"ammo" 30 	{max 540}}
			{item "76239_75" 			"ammo" 75 	{max 450}}
			{item "76239_100" 			"ammo" 100	{max 600}}
			{item "76242_6" 			"ammo" 6 	{max 24}}
			{item "76251_5" 			"ammo" 5 	{max 35}}
			{item "76251_10aw" 			"ammo" 10 	{max 70}}
			{item "76251_10fr" 			"ammo" 10 	{max 70}}
			{item "76251_20fn" 			"ammo" 20 	{max 140}}
			{item "76251_20g3" 			"ammo" 20 	{max 140}}
			{item "76251_20m14" 		"ammo" 20 	{max 140}}
			{item "76251_20jp" 			"ammo" 20 	{max 140}}
			{item "76251_30bren" 		"ammo" 30 	{max 210}}
			{item "76251_35" 			"ammo" 35 	{max 245}}
			{item "76251_100" 			"ammo" 100	{max 600}}
			{item "76254_10" 			"ammo" 10 	{max 70}}
			{item "76254_30" 			"ammo" 30 	{max 360}}
			{item "76254_50" 			"ammo" 50 	{max 600}}
			{item "76254_100" 			"ammo" 100	{max 600}}
			{item "76263_20" 			"ammo" 20	{max 140}}
			{item "76263_100" 			"ammo" 100	{max 600}}
			{item "76517_20" 			"ammo" 20 	{max 140}}
			{item "79257_10" 			"ammo" 10 	{max 70}}
			{item "79257_50" 			"ammo" 50 	{max 300}}
			{item "127108_100" 			"ammo" 200	{max 1200}}
			{item "size12_ammo" 		"ammo" 10 	{max 80}}
			{item "hmgun" 				"ammo" 50 	{max 300}	{value 2}}
			;>>
			{item "grenade" 			"decoy" 1 	{max 1}		{value 2}}
			{item "bandage"						1 	{max 5}}
			;>>
			{item "agi3x40_rocket" 		"ammo" 1 {max 6}}
			{item "carl_gustav_rocket" 	"ammo" 1 {max 6}}			
			{item "law80_rocket" 		"ammo" 1 {max 6}}
			{item "lrac73_rocket" 		"ammo" 1 {max 6}}	
			{item "lracf1_rocket" 		"ammo" 1 {max 6}}		
			{item "m20a1_rocket" 		"ammo" 1 {max 6}}	
			{item "m57a2_rocket" 		"ammo" 1 {max 6}}	
			{item "m67_rocket" 			"ammo" 1 {max 6}}
			{item "m79rpg_rocket" 		"ammo" 1 {max 6}}		
			{item "m202_rocket" 		"ammo" 1 {max 6}}
			{item "m386_rifle_grenade" 	"ammo" 1 {max 24}}
			{item "vog25_rifle_grenade" "ammo" 1 {max 24}}			
			{item "p27rpg_rocket" 		"ammo" 1 {max 6}}			
			{item "panzerfaust3_rocket" "ammo" 1 {max 6}}		
			{item "pf98_rocket" 		"ammo" 1 {max 6}}		
			{item "rl100_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg7_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg29_rocket" 		"ammo" 1 {max 6}}			
			{item "smaw_rocket" 		"ammo" 1 {max 6}}			
			{item "type56_rocket" 		"ammo" 1 {max 6}}		
			{item "type65_rocket" 		"ammo" 1 {max 6}}		
			{item "type67_rifle_grenade" "ammo" 1 {max 24}}		
			{item "type69_rocket" 		"ammo" 1 {max 6}}		
			{item "type70_rocket" 		"ammo" 1 {max 6}}
			{item "type89_rocket" 		"ammo" 1 {max 6}}
			;>>
			{item "mortar" "fg" 		"ammo" 5 {max 30}		{value 2}}
			{item "mortar107" "fg" 		"ammo" 5 {max 30}		{value 2}}
			{item "mortar120" "fg" 		"ammo" 5 {max 30}		{value 2}}
		}
		{radius 			6}
		{resupplyPeriod 	3}
		{regenerationPeriod 30}
		{limit 				75}
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.8}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)

(define "box_ammo_art"
	{extender "supply_zone"
		{resupply
            {item "22lr_176" 			"ammo" 176 	{max 352}}
			{item "47g11_45" 			"ammo" 45 	{max 315}}
			{item "338_5" 				"ammo" 5 	{max 35}}
			{item "918_8" 				"ammo" 8 	{max 32}}
			{item "918_20" 				"ammo" 20 	{max 60}}
			{item "918_25" 				"ammo" 25 	{max 100}}
			{item "919_8" 				"ammo" 8 	{max 32}}
			{item "919_13" 				"ammo" 13 	{max 52}}
			{item "919_15" 				"ammo" 15 	{max 60}}
			{item "919_17" 				"ammo" 17 	{max 68}}
			{item "919_30" 				"ammo" 30 	{max 210}}
			{item "919_30fr" 			"ammo" 30 	{max 210}}
			{item "919_30jp" 			"ammo" 30 	{max 210}}
			{item "919_32" 				"ammo" 32 	{max 224}}
			{item "919_34" 				"ammo" 34 	{max 238}}
			{item "919_36" 				"ammo" 36 	{max 252}}
			{item "919_40" 				"ammo" 40 	{max 280}}
			{item "939_20" 				"ammo" 20 	{max 140}}
			{item "1143_7" 				"ammo" 7 	{max 28}}
			{item "1143_20_thompson" 	"ammo" 20 	{max 200}}
			{item "1143_30" 			"ammo" 30 	{max 150}}
			{item "5821_15" 			"ammo" 15 	{max 105}}
			{item "5842_10" 			"ammo" 10 	{max 70}}
			{item "5842_75" 			"ammo" 75 	{max 450}}
			{item "5842_200" 			"ammo" 200 	{max 600}}
			{item "12799_5" 			"ammo" 10	{max 35}}
			{item "12799_10" 			"ammo" 10	{max 70}}
			{item "12799_100" 			"ammo" 100	{max 900}}
			{item "54539_30" 			"ammo" 30 	{max 210}}
			{item "54539_45" 			"ammo" 45 	{max 540}}
			{item "54539_75" 			"ammo" 75 	{max 450}}
			{item "55645_20" 			"ammo" 20 	{max 140}}
			{item "55645_20sg" 			"ammo" 20 	{max 140}}
			{item "55645_25fr" 			"ammo" 25 	{max 175}}
			{item "55645_25hk" 			"ammo" 25 	{max 175}}
			{item "55645_30ar" 			"ammo" 30 	{max 210}}
			{item "55645_30aug" 		"ammo" 30 	{max 210}}
			{item "55645_30g36" 		"ammo" 30 	{max 210}}
			{item "55645_30jp" 			"ammo" 30 	{max 210}}
			{item "55645_30za" 			"ammo" 30 	{max 210}}
			{item "55645_35" 			"ammo" 35 	{max 245}}
			{item "55645_200" 			"ammo" 200 	{max 800}}
			{item "5842_30" 			"ammo" 30 	{max 210}}
			{item "75054_5" 			"ammo" 5 	{max 35}}
			{item "75054_10" 			"ammo" 10 	{max 70}}
			{item "75054_100" 			"ammo" 100	{max 600}}
			{item "76217_9" 			"ammo" 9 	{max 36}}
			{item "76225_8" 			"ammo" 8 	{max 32}}
			{item "76225_9" 			"ammo" 9 	{max 36}}
			{item "76225_20" 			"ammo" 20 	{max 140}}
			{item "76225_30" 			"ammo" 30 	{max 210}}
			{item "76225_35" 			"ammo" 35 	{max 245}}
			{item "76225_71" 			"ammo" 71 	{max 213}}
			{item "76239_10" 			"ammo" 10 	{max 70}}
			{item "76239_20" 			"ammo" 20 	{max 140}}
			{item "76239_30" 			"ammo" 30 	{max 210}}
			{item "76239_40" 			"ammo" 30 	{max 540}}
			{item "76239_75" 			"ammo" 75 	{max 450}}
			{item "76239_100" 			"ammo" 100	{max 600}}
			{item "76242_6" 			"ammo" 6 	{max 24}}
			{item "76251_5" 			"ammo" 5 	{max 35}}
			{item "76251_10aw" 			"ammo" 10 	{max 70}}
			{item "76251_10fr" 			"ammo" 10 	{max 70}}
			{item "76251_20fn" 			"ammo" 20 	{max 140}}
			{item "76251_20g3" 			"ammo" 20 	{max 140}}
			{item "76251_20m14" 		"ammo" 20 	{max 140}}
			{item "76251_20jp" 			"ammo" 20 	{max 140}}
			{item "76251_30bren" 		"ammo" 30 	{max 210}}
			{item "76251_35" 			"ammo" 35 	{max 245}}
			{item "76251_100" 			"ammo" 100	{max 600}}
			{item "76254_10" 			"ammo" 10 	{max 70}}
			{item "76254_30" 			"ammo" 30 	{max 360}}
			{item "76254_50" 			"ammo" 50 	{max 600}}
			{item "76254_100" 			"ammo" 100	{max 600}}
			{item "76263_20" 			"ammo" 20	{max 140}}
			{item "76263_100" 			"ammo" 100	{max 600}}
			{item "76517_20" 			"ammo" 20 	{max 140}}
			{item "79257_10" 			"ammo" 10 	{max 70}}
			{item "79257_50" 			"ammo" 50 	{max 300}}
			{item "127108_100" 			"ammo" 200	{max 1200}}
			{item "size12_ammo" 		"ammo" 10 	{max 80}}
			{item "hmgun" 				"ammo" 50 	{max 300}	{value 2}}
			;>>
			{item "grenade" 			"decoy" 1 	{max 1}		{value 2}}
			{item "bandage"						1 	{max 5}}
			;>>
			{item "agi3x40_rocket" 		"ammo" 1 {max 6}}
			{item "carl_gustav_rocket" 	"ammo" 1 {max 6}}			
			{item "law80_rocket" 		"ammo" 1 {max 6}}
			{item "lrac73_rocket" 		"ammo" 1 {max 6}}	
			{item "lracf1_rocket" 		"ammo" 1 {max 6}}		
			{item "m20a1_rocket" 		"ammo" 1 {max 6}}	
			{item "m57a2_rocket" 		"ammo" 1 {max 6}}	
			{item "m67_rocket" 			"ammo" 1 {max 6}}
			{item "m79rpg_rocket" 		"ammo" 1 {max 6}}		
			{item "m202_rocket" 		"ammo" 1 {max 6}}
			{item "m386_rifle_grenade" 	"ammo" 1 {max 24}}
			{item "vog25_rifle_grenade" "ammo" 1 {max 24}}			
			{item "p27rpg_rocket" 		"ammo" 1 {max 6}}			
			{item "panzerfaust3_rocket" "ammo" 1 {max 6}}		
			{item "pf98_rocket" 		"ammo" 1 {max 6}}		
			{item "rl100_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg7_rocket" 		"ammo" 1 {max 6}}		
			{item "rpg29_rocket" 		"ammo" 1 {max 6}}			
			{item "smaw_rocket" 		"ammo" 1 {max 6}}			
			{item "type56_rocket" 		"ammo" 1 {max 6}}		
			{item "type65_rocket" 		"ammo" 1 {max 6}}		
			{item "type67_rifle_grenade" "ammo" 1 {max 24}}		
			{item "type69_rocket" 		"ammo" 1 {max 6}}		
			{item "type70_rocket" 		"ammo" 1 {max 6}}
			{item "type89_rocket" 		"ammo" 1 {max 6}}
			;>>
			{item "mortar" 		"fg" 	"ammo" 5 {max 30}	{value 2}}
			{item "mortar107" 	"fg" 	"ammo" 5 {max 30}	{value 2}}
			{item "mortar120" 	"fg" 	"ammo" 5 {max 30}	{value 2}}
			;>>
			{item "bullet20" 	"zenite" "ammo" 10 {max 100}{value 2}}
			{item "bullet23" 	"zenite" "ammo" 500 {max 8000}{value 2}}
			{item "bullet25" 	"zenite" "ammo" 600 {max 2000}{value 2}}
			{item "bullet30" 	"fg" "ammo" 90 {max 1000}{value 2}}
			{item "bullet30" 	"zenite" "ammo" 600 {max 2000}{value 2}}
			{item "bullet35" 	"zenite" "ammo" 600 {max 1000}{value 2}}
			{item "bullet37" 	"zenite" "ammo" 10 {max 600}{value 2}}
			{item "bullet40" 	"fg" "ammo" 100 {max 1200}{value 2}}
			{item "bullet40" 	"zenite" "ammo" 10 {max 600}{value 2}}
			{item "bullet57" 	"ap" 	"ammo" 3 {max 30}{value 2}}
			{item "bullet57" 	"fg" 	"ammo" 3 {max 25}{value 2}}
			{item "bullet73" 	"ap" 	"ammo" 3 {max 30}{value 2}}
			{item "bullet73" 	"fg" 	"ammo" 3 {max 25}{value 2}}
			{item "bullet76" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet76" 	"apcr" 	"ammo" 2 {max 10}{value 2}}
			{item "bullet76" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet76" 	"heat" 	"ammo" 1 {max 10}{value 5}}
			{item "bullet76" 	"hesh" 	"ammo" 1 {max 10}{value 5}}
			{item "bullet82" 	"ap" 	"ammo" 3 {max 30}{value 2}}
			{item "bullet82" 	"fg" 	"ammo" 3 {max 25}{value 2}}	
			{item "bullet85" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet85" 	"apcr" 	"ammo" 2 {max 10}{value 2}}
			{item "bullet85" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet85" 	"heat" 	"ammo" 1 {max 10}{value 5}}
			{item "bullet90" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet90" 	"apcr" 	"ammo" 2 {max 10}{value 2}}
			{item "bullet90" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet90" 	"heat" 	"ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet90usa" "ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet90usa" "apcr" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet90usa" "fg" 	"ammo" 2 {max 15}{value 2}}	
			{item "bullet90usa" "heat" 	"ammo" 2 {max 20}{value 2}}	
			;>>
			{item "bullet100b" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			;>>
			{item "bullet100" 	"ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"ap_a" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"ap_b" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"ap_c" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"apcr" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"apds" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100" 	"fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet100" 	"heat" 	"ammo" 2 {max 10}{value 2}}
			;>>
			{item "bullet100chi" "ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet100chi" "apds" "ammo" 2 {max 20}{value 2}}
			{item "bullet100chi" "fg" 	"ammo" 2 {max 15}{value 2}}
			{item "bullet100chi" "heat" "ammo" 2 {max 10}{value 2}}
			;>>
			{item "bullet105usa" "ap" 	"ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_a" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_b" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_c" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "ap_d" "ammo" 2 {max 20}{value 2}}
			{item "bullet105usa" "heat" "ammo" 1 {max 10}{value 5}}
			{item "bullet105usa" "heat_a" "ammo" 1 {max 10}{value 5}}
			{item "bullet105usa" "hesh" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet105fra" "ap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105fra" "ap_a" "ammo" 2 {max 20}{value 2}}
			{item "bullet105fra" "fg" "ammo" 1 {max 10}{value 5}}
			{item "bullet105fra" "heat" "ammo" 1 {max 10}{value 5}}
			{item "bullet105fra" "heat_a" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet105" "ap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "ap_a" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "ap_b" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "ap_jap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105" "fg" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "heat" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "heat_jap" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "hesh" "ammo" 1 {max 10}{value 5}}
			{item "bullet105" "hesh_jap" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet105chi" "ap" "ammo" 2 {max 20}{value 2}}
			{item "bullet105chi" "hesh" "ammo" 1 {max 10}{value 5}}
			{item "bullet105chi" "heat" "ammo" 1 {max 10}{value 5}}
			;>>
			{item "bullet106" "ap" "ammo" 2 {max 15}{value 2}}
			{item "bullet106" "fg" "ammo" 1 {max 10}{value 2}}
			;>>
			{item "bullet115" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"ap_a" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"ap_b" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"ap_c" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet115" 	"fg" 		"ammo" 2 	{max 15}	{value 2}}
			{item "bullet115" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet115" 	"heat_a" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120usa" "ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120usa" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120usa" "heat" 	"ammo" 1 	{max 10}	{value 5}}
			{item "bullet120usa" "mpat" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120fra" "ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120fra" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120fra" "heat" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120brit" "ap"   	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_b" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_c" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "ap_d" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120brit" "hesh" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120" 	"ap_a" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120" 	"ap_b" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet120" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet120" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet120rcl" "hesh" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet122" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet122" 	"apcr" 		"ammo" 2 	{max 10}	{value 2}}
			{item "bullet122" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet125" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_a" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_a_yug" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_b" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_c" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"ap_d" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet125" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet125chi" "ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125chi" "ap_a" 	"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125chi" "fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet125chi" "heat" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet125b" 	"ap" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125b" 	"apu" 		"ammo" 2 	{max 20}	{value 2}}
			{item "bullet125b" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet125b" 	"heat" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet130" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet152" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet152" 	"cluster" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet155" 	"fg" 		"ammo" 1 	{max 10}	{value 5}}
			{item "bullet155" 	"cluster" 	"ammo" 1 	{max 10}	{value 5}}
			;>>
			{item "bullet165" 	"hesh" 			   1 	{max 10}	{value 5}}
			;>>
			{item "bullet170" 	"fg" 		"ammo" 1 	{max 5}		{value 5}}
			{item "bullet203" 	"fg" 		"ammo" 1 	{max 5}		{value 5}}
			;>>
			{item "rocket57" 	"fg" 		"ammo" 10 	{max 60}	{value 2}}
			{item "rocket70" 	"fg" 		"ammo" 7 	{max 14}	{value 2}}
			{item "rocket80" 	"fg" 		"ammo" 20 	{max 80}	{value 2}}
			;>>
			{item "bullet100" 	"arkan" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet100" 	"bastion" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet115" 	"arkan"  	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"angora" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"kobra" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"invar" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"refleks" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"sheksna" 	"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125" 	"svir" 		"ammo" 1 	{max 5}		{value 5}}
			{item "bullet125b" 	"9m125" 	"ammo" 1 	{max 5}		{value 5}}	
			;>>
			{item "9m33" 					"ammo" 4 	{max 8}		{value 5}}
			{item "9m311" 					"ammo" 4 	{max 8}		{value 5}}
			{item "9m333" 					"ammo" 4 	{max 8}		{value 5}}
			{item "igla" 					"ammo" 1 	{max 8}		{value 5}}
			{item "stinger" 				"ammo" 1 	{max 8}		{value 5}}
			{item "roland" 					"ammo" 1 	{max 8}		{value 5}}
			{item "rapier" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hq61a" 					"ammo" 4 	{max 8}		{value 5}}
			;>>
			{item "9k127" 					"ammo" 6 	{max 24}	{value 20}}
			{item "9m120" 					"ammo" 4 	{max 16}	{value 20}}
			{item "bulsae" 					"ammo" 5 	{max 8}		{value 5}}
			{item "dragon" 					"ammo" 1 	{max 4}		{value 5}}
			{item "fagot"	 				"ammo" 1 	{max 8}		{value 5}}
			{item "hellfire" 				"ammo" 4 	{max 8}		{value 20}}
			{item "hj8" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hj9" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hj73" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hot" 					"ammo" 1 	{max 8}		{value 5}}
			{item "hot3"					"ammo" 4 	{max 8}		{value 20}}
			{item "itow"					"ammo" 1 	{max 8}		{value 5}}
			{item "jyu_mat" 				"ammo" 1 	{max 8}		{value 5}}
			{item "konkurs" 				"ammo" 4 	{max 8}		{value 5}}
			{item "malyutka" 				"ammo" 4 	{max 8}		{value 5}}
			{item "milan" 					"ammo" 1 	{max 8}		{value 5}}
			{item "milan2" 					"ammo" 1 	{max 8}		{value 5}}
			{item "pars" 					"ammo" 4 	{max 8}		{value 20}}
			{item "ss11" 					"ammo" 1 	{max 8}		{value 5}}
			{item "susongpo" 				"ammo" 4 	{max 8}		{value 5}}
			{item "swingfire" 				"ammo" 1 	{max 8}		{value 5}}
			{item "tow" 					"ammo" 1 	{max 8}		{value 5}}
			{item "tow2" 					"ammo" 1 	{max 8}		{value 5}}
			;>>
			{item "rocket57_b" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket70_b" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket106" 	"fg" 		"ammo" 4 	{max 38}	{value 5}}
			{item "rocket110" 	"fg" 		"ammo" 8 	{max 72}	{value 5}}
			{item "rocket122" 	"fg" 		"ammo" 10 	{max 80}	{value 5}}
			{item "rocket122" 	"mine" 		"ammo" 10 	{max 80}	{value 5}}
			{item "rocket122" 	"tbc" 		"ammo" 10 	{max 80}	{value 5}}
			{item "rocket128" 	"fg" 		"ammo" 4 	{max 64}	{value 5}}
			{item "rocket128_a" "fg" 		"ammo" 8 	{max 64}	{value 5}}
			{item "rocket220" 	"fg" 		"ammo" 4 	{max 32}	{value 5}}
			{item "rocket227" 	"cluster" 	"ammo" 6 	{max 24}	{value 5}}
			{item "rocket227" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket240" 	"fg" 		"ammo" 6 	{max 48}	{value 5}}
			{item "rocket262" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket300" 	"cluster" 	"ammo" 6 	{max 24}	{value 5}}
			{item "rocket300" 	"fg" 		"ammo" 6 	{max 24}	{value 5}}
			{item "rocket300" 	"tbc" 		"ammo" 6 	{max 24}	{value 5}}
		}
		{radius 			10}
		{resupplyPeriod 	2}
		{regenerationPeriod 30}
		{limit 				500}
	}
	{DecalView supply_zone
		{Sprite "supply_zone.ebm"
			{Visibility 0.8}
		}
		{Layer grounddynamic}
		{Visible 0}
	}
)