
		{"nato"
			{"sas" "SAS"}
			{"nato_mgun" "Пулеметчик НАТО"}
			{"nato_soilder" "Солдат НАТО"}
			{"nato_snaiper" "Снайпер НАТО"}
			{"scout" "Разведчик НАТО"}
			{"nato_soilder" "Солдат НАТО"}
			{"nato_officer_1" "Офицер НАТО"}
			{"nato_bazooker" "Гранатометчик НАТО"}
			{"nato_soilder_2" "Солдат НАТО"}
			{"nato_tankman" "Танкист НАТО"}
			{"nato_pilot" "Пилот НАТО"}
		}	
				
		
			
	{"red_culac"
			{"astratov" "Астратов Геогрий"}
			{"bazooker" "Гранатометчик КК"}
			{"engineer" "Инженер КК"}
			{"leonov" "Леонов Кардинал Геогрий"}
			{"malash" "Николай Малашенко"}
			{"soilder" "Рядовой КК"}
			{"medic" "Санитар КК"}
			{"persey" "Персей"}
			{"mgun" "Пулеметчик КК"}
			{"spec_snaiper" "Снайпер СП"}
			{"radioman" "Радист КК"}
			{"spec" "Спецназ КК"}
			{"vdv_soilder" "Десатник"}
	}	
	
	