{"rus_bron_medik" "Бронежилет санитара РФ"}
{"rus_bron_mgun" "Бронижелет пулеметчика РФ"}
{"rus_bron_oficer" "Офицерский бронижилет РФ"}
{"rus_bron_rpg" "Бронежилет Гранатомечика РФ"}
{"rus_bron_sniper" "Бронежилет Снайпера РФ" } 
{"rus_oficer_planshet" "Офицерский планшет РФ"}
{"rus_afg_ermolka" "Афганская ермолка"}
{"rus_afg_hat_new" "Афганская кепка"}
{"rus_afg_sh68" "СШ-68"}
{"rus_afg_vdvberet_new" "берет ВДВ"}
{"rus_maska1_visordown_new" ""}
{"sas_helmet" "Шлем SAS"}
{"Shapka1_rus" "Шапка-ушанка"}
{"sov_helmet_ssh60" "СШ-60"}
{"sov_helmet_ssh60_medic" "СШ-60 санитара"} 
{"soviet_pilot_helmet" "Пилотный шлемфон"}
{"sas_mask" "Противогаз SAS"}
{"platok_1" "Платок"}
{"Platok_mask" "Платок-маска"}
{"spec_gaz" "Противогаз"}
{"beret_vdv_rad" "Берет ВДВ радиста"}
{"Kapushon" "Капюшон"}
{"usa_beret_officer" "Берет офицера США"}
{"razgruz" "Разгруз"}
{"rus_radio_station" "Радиостанция РФ"} 
{"belt_a" "Разгруз"} 
{"l2a2_grenade" "ПП l2a2"}
{"l109_grenade" "ПП l109"}
{"rgd" "РГД"}
{"rgn" "РГН"}
{"jap_hat1" "Японская кепка"}
{"jap_helmet1" "Японская каска"}
{"jap_helmet2" "Японская каска"}
{"jap_helmet2_medic" "Японская каска медика"}
{"jap_officercap" "Японская офицерская фуражка"}
{"rus_afg_sh68_ermolka" "СШ-68"}
{"rus_afg_sh68_hat_new" "СШ-68"}
{"rus_afg_ushanka_new" "Шапка-ушанка"}
{"rus_afg_vdvberet_new" "Афганский берет"}
{"usa_helmet_1" "Американская каска"}
{"usa_helmet_2" "Американская каска"}
{"radio_station" "Радиостанция"}
{"tushonka" "Тушенка"}
{"notebook" "Ноутбук"}
{"usa_helmet_3" "Американская каска"}
{"usa_tank_helm" "Шлемофон танкиста США"}
{"bron_1_brit" "Британский бронежилет"}
{"bron_2_brit" "Британский бронежилет"}
{"bron_2_france" "Французский бронежилет"}
{"bron_3_brit" "Британский бронежилет"}
{"bron_med_france" "Брит. медицинский бронежилет"}
{"rus_bron_specnaz" "Бронежилет спецназа РФ"}
{"fsl01" "Дымовая граната"}
{"l2a2_grenade" "L2A2"}
{"l109_grenade" "HG 85"}
{"m26a2_grenade" "M26"}
{"m61_grenade" "M61"}
{"m61_grenade" "M61"}
{"m61_grenade" "M61"}
{"m61_grenade" "M61"}
{"m61_grenade" "M61"}
{"m67_grenade" "M67"}
{"of37_grenade" "OF37"} 
{"type67_grenade" "Type 67"}
{"rus_afg_sh68_ermolka" "СШ-68 Ермолка"}
{"rus_afg_sh68_ermolka_new" "Ермолка"}
{"rus_afg_sh68_hat_new" "СШ-68"}
{"usa_tank_helm" "Американский шлемофон танксита"}
{"tankhelmet_rus" "Шлемофон танкиста"}