
		{"rpg7" "РПГ-7"}
		{"rpg27" "РПГ-27"}
		{"rpg18" "РПГ-18"}
		{"rpg-29" "rpg-29"}
		{"m249" "M249 SAW"}
		{"pkm" "ПКМ"}
		{"rpk74" "РПК-74"}
		{"aps" "АПС"}
		{"glock17" "Glock-17"}
		{"l9_pistol" "Browning Hi-Power"}
		{"m9_beretta" "Beretta M9"}
		{"l1a1" "L1a1"}
		{"svd" "СВД"}
		{"vintorez" "Винторез"}
		{"l96a1" "L96A1"}
		{"m90" "Barrett M90"}
		{"stg943" "Wieger"}
		{"ak74" "АК-74"}
		{"akms" "АКМС"}
		{"mat49" "ПП MAT-49"}
		{"l2a3_sterling" "Sterling L2"}
		{"m3a1_smg" "ПП M3"}
		{"makarov" "ПМ"}
		{"m240" "M240"}
		{"smaw" "SMAW"}
		{"aks74u" "АКМ-74У"}
		{"svd12" "СВД-12"}
		{"p22" "Walther P22"}
		{"jap64smg" "Type 64"} 
		{"jap89smg" "Type 89"} 
		{"sck66" "М66"}
		{"rpk74_1" "РПК-74"}
		{"m16a1_s " "М16"}
		{"m16a2_s" "M16"}
		{"m79" "M79"}
		{"jap62mgun" "Type 62"}
		{"jap62mgun" "Type 62"}
		{"eryx" "ERYX"}
		{"lrac73" "LRAC"}
		{"famas" "FAMAS"}
		{"nsvt" "НСВТ"}
		{"minimi" "FN Minimi"}
		{"pkmt" "ПКМТ"}
		{"PKT" "ПКТ"}
		{"m21" "M21"}
		{"" ""}
		
		
		
