; Real Flamethrower by Cosalcea:

; Improving grenade collider
(include "../rf/grenade.inc")

; Construction burning settings
(include "../rf/construction/burning.inc")

; Misc settings
(include "../rf/construction/special.inc")

; General vehicle burning settings
(include "../rf/vehicle.inc")

; Unarmored vehicle burning settings
(include "../rf/car.inc")

; Things about soldiers
(include "../rf/human.inc")

; Things about tanks
(include "../rf/tank.inc")

; Flame!
(include "../rf/flame.inc")